# Generated by Django 5.1.5 on 2025-02-04 00:05

import receipts.models.receipt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptimage',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptimage',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptimage',
            name='image',
            field=models.ImageField(upload_to=receipts.models.receipt.ReceiptImage.upload_to),
        ),
    ]
